version: '3'
services:
  chalkbot:
    container_name: ChalkBot
    build:
      context: .
      dockerfile: Dockerfile
    image: chalkbot:latest
    profiles:
      - bot
  chalkbot-mongo:
    container_name: chalkbot-mongodb
    image: mongo:4-bionic
    ports:
      - '27017:27017'
    volumes:
      - ./db-data:/data/db
    profiles:
      - bot